"""change tag name collation to utf8mb4_general_ci

Revision ID: 4f308d092386
Revises: aa084f2c60f6
Create Date: 2024-01-23 21:18:51.543256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f308d092386'
down_revision = 'aa084f2c60f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'canonical_name', type_=sa.types.VARCHAR(255, collation='utf8mb4_general_ci'))
    op.alter_column('tag', 'name', type_=sa.types.VARCHAR(255, collation='utf8mb4_general_ci'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'canonical_name', type_=sa.types.VARCHAR(255))
    op.alter_column('tag', 'name', type_=sa.types.VARCHAR(255))
    # ### end Alembic commands ###
