"""delete top_illust_id

Revision ID: 855f7341cdd0
Revises: bc6b24cbc379
Create Date: 2022-04-07 02:28:12.826108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '855f7341cdd0'
down_revision = 'bc6b24cbc379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'top_illust_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('top_illust_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
