"""add column artwork.rating

Revision ID: e91f6a8af37b
Revises: f4631d335c43
Create Date: 2022-04-12 02:43:03.471350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91f6a8af37b'
down_revision = 'f4631d335c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('rating', sa.Enum('safe', 'r_18', 'r_18g', name='artworkratingenum'), server_default='safe', nullable=False))
    op.create_index('rating_created_at', 'artwork', ['rating', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('rating_created_at', table_name='artwork')
    op.drop_column('artwork', 'rating')
    # ### end Alembic commands ###
