"""drop column artwork.top_illust_id

Revision ID: f4631d335c43
Revises: 9a509324aa66
Create Date: 2022-04-11 20:38:08.799256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f4631d335c43'
down_revision = '9a509324aa66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'top_illust_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('top_illust_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
