version: '3'
services:
  api:
    build:
      context: ./api
    command: /app/script/docker-main.sh
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./api/public:/app/public
      - ./api/script:/app/script
      - ./api/alembic.ini:/app/alembic.ini
      - ./api/tests:/app/tests
      - ./api/db:/app/db
    environment:
      - DB_URL=${DB_URL:-mysql+mysqlconnector://root@db/goduploader}
      - DB_URL_TEST=mysql+mysqlconnector://root@db/goduploader_test
      - FLASK_APP=src/goduploader/web
      - GYAZO_ACCESS_TOKEN=${GYAZO_ACCESS_TOKEN}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - PUBLIC_FOLDER=/app/public
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
    depends_on:
      - db
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
  slack-event:
    build:
      context: ./slack-event
    ports:
      - 127.0.0.1:5001:5001
    environment:
      - BIND_ADDRESS=:5001
      - TARGET_DOMAIN=godillustuploader.kmc.gr.jp
      - EXTERNAL_URL_BASE=http://localhost:3000
      - INTERNAL_URL_BASE=http://api:5000
      - GRAPHQL_API_ENDPOINT=http://api:5000/api/graphql
      - GYAZO_ACCESS_TOKEN=${GYAZO_ACCESS_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_VERIFICATION_TOKEN=${SLACK_VERIFICATION_TOKEN}
      - SLACK_TOKEN=${SLACK_TOKEN}
    depends_on:
      - api
volumes:
  mysql_data:
