version: '3'
services:
  api:
    build:
      context: ./api
    command: /app/script/docker-main.sh
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./api/public:/app/public
      - ./api/script:/app/script
      - ./api/alembic.ini:/app/alembic.ini
      - ./api/tests:/app/tests
      - ./api/db:/app/db
    environment:
      - DB_URL=${DB_URL:-mysql+mysqlconnector://root@db/goduploader}
      - DB_URL_TEST=${DB_URL_TEST:-mysql+mysqlconnector://root@db/goduploader_test}
      - FLASK_APP=src/goduploader/web
      - GYAZO_ACCESS_TOKEN=${GYAZO_ACCESS_TOKEN}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - PUBLIC_FOLDER=/app/public
      - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
      - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - USE_DEVELOPMENT_SERVER=1
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
volumes:
  mysql_data:
