name: API

env:
  TZ: Asia/Tokyo
  PYTHON_VERSION: "3.14"
  POETRY_VERSION: "2.2.1"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api.yml
      - api/**
  pull_request:
    paths:
      - .github/workflows/api.yml
      - api/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: 'sqlite:///:memory:'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      # ref: api/Dockerfile
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libjpeg-dev libwebp-dev

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: ./api/poetry.lock

      - uses: abatilo/actions-poetry@0dd19c9498c3dc8728967849d0d2eae428a8a3d8 # v4
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: api/.venv
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-

      - run: poetry install
        working-directory: ./api

      - run: poetry run pytest
        working-directory: ./api
        env:
          DB_URL: 'sqlite:///:memory:'

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build Docker image
        run: docker build ./api
