name: API

env:
  TZ: Asia/Tokyo
  PYTHON_VERSION: "3.14"
  POETRY_VERSION: "2.2.1"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api.yml
      - api/**
  pull_request:
    paths:
      - .github/workflows/api.yml
      - api/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: 'sqlite:///:memory:'
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      # ref: api/Dockerfile
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libjpeg-dev libwebp-dev imagemagick webp

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: ./api/poetry.lock

      - uses: abatilo/actions-poetry@fd0e6716a0de25ef6ade151b8b53190b0376acfd # v3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}

      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3
        with:
          path: api/.venv
          key: ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PYTHON_VERSION }}-poetry-

      - run: poetry install
        working-directory: ./api

      - run: poetry run pytest
        working-directory: ./api
        env:
          DB_URL: 'sqlite:///:memory:'
