name: Build front

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: front/yarn.lock

      - run: cd front && yarn install --frozen-lockfile

      - run: cd front && yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: front-${{github.sha}}
          path: front/build/
