name: Slack Event Handler

env:
  TZ: Asia/Tokyo

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/slack-event.yml
      - slack-event/**
  pull_request:
    paths:
      - .github/workflows/slack-event.yml
      - slack-event/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: ./slack-event/go.mod

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go

      - run: go build
        working-directory: ./slack-event

      - run: go test -v ./...
        working-directory: ./slack-event

  build:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: kmc-jp/goduploader-graphql-slack-event-handler
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Determine whether to push
        id: determine-push
        run: echo ::set-output name=push::${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value={{sha}}-{{date 'YYYYMMDDHHmmss'}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./slack-event
          push: ${{ steps.determine-push.outputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=slack-event
          cache-to: type=gha,mode=max,scope=slack-event
